[package]
name = "datafusion-ducklake"
version = "0.0.2"
edition = "2024"
authors = ["zac@hotdata.dev", "shefeek@hotdata.dev"]
description = "DuckLake query engine for rust, built with datafusion."
license = "Apache-2.0"
repository = "https://github.com/hotdata-dev/datafusion-ducklake"
homepage = "https://github.com/hotdata-dev/datafusion-ducklake"
documentation = "https://docs.rs/datafusion-ducklake"
readme = "README.md"
keywords = ["datafusion", "duckdb", "ducklake", "iceberg", "datalake"]
categories = ["database", "filesystem"]
exclude = ["datafusion-ducklake.iml", "target", "tests/test_data"]

[dependencies]
datafusion = "50.1.0"
arrow = "56.2.0"
parquet = "56.2.0"
object_store = { version = "0.12.4", features = ["aws"] }
url = "2.5"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
duckdb = { version = "1.4.1", features = ["bundled"] }
futures = "0.3"
tracing = "0.1"
thiserror = "2.0"

[dev-dependencies]
testcontainers = "0.23"
testcontainers-modules = { version = "0.11", features = ["minio"] }
tempfile = "3.14"
anyhow = "1.0"
aws-sdk-s3 = "1.75"
aws-credential-types = "1.2"
sqllogictest = "0.28"
regex = "1"
async-trait = "0.1"
env_logger = "0.11"
glob = "0.3"

[[test]]
name = "sqllogictests"
path = "tests/sqllogictests/runner.rs"
harness = false

[features]
# Allow skipping tests that use docker (in CI, macos doesn't support docker).
skip-tests-with-docker = []